title: Alessandro Mantoan
email: alessandro.mantoan.dp@gmail.com
description: Archivista digitale specializzato in preservazione audiovisiva e patrimonio multimediale.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alessandro-mantoan-dp.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  alessandro-mantoan-dp

# Build settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "neon"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name: "Alessandro Mantoan"
  bio: "Archivista digitale. Preservazione audiovisiva, patrimonio videoludico, standard OAIS."
  location: "Italia"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alessandro-mantoan-dp"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true