title: Alessandro Mantoan
email: alessandro.mantoan.dp@gmail.com
description: Archivista digitale specializzato in preservazione multimediale.
baseurl: ""
url: "https://alessandro-mantoan-dp.github.io"
github_username: alessandro-mantoan-dp

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "neon"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  bio: "Archivista digitale. Preservazione audiovisiva, patrimonio culturale multimediale, standard OAIS."
  location: "Desio, MB, Italia"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/alessandro-mantoan000/"

defaults:
  - scope:
      path: ""
    values:
      author_profile: true
      header:
        overlay_image: /assets/images/header.png
        overlay_filter: 0.5